# general site settings
title           = "Workloads"
googleAnalytics = "" # Add your identifier. For example UA-99631805-1.

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
    unsafe = true

  [markup.highlight]
    codeFences  = true
    guessSyntax = true
    noClasses   = false

# items for main menu, see https://gohugo.io/content-management/menus/#define-in-site-configuration
[menu]
  [[menu.main]]
    identifier = "home"
    name       = "Home"
    url        = "/"
    weight     = 1

  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
    weight     = 2

[params]
  logo        = "" # You can add own logo. For example "/images/logo.png".
  description = "Workloads v1, a Hugo Theme based on Norlin."

  [params.authors]

    [params.authors.kerim]
      name     = "Kerim Satirli"
      avatar   = "/images/kerim.jpg"
      bio      = "Kerim is a senior developer advocate at HashiCorp, where he coaches operators and developers on sustainable infrastructure and orchestration workflows."
      github   = "https://github.com/ksatirli"
      linkedin = "https://www.linkedin.com/in/kerimsatirli/"
      twitter  = "https://twitter.com/ksatirli"


  [params.fontawesome]
    identifier = "f8764d0198"

  [params.hero]
    hero__title       = "Robert Wilson"
    hero__description = "Thoughts, stories and ideas."
    hero__image       = "/images/01.jpg"

  [[params.social]]
    icon = "fa-brands fa-github"
    name = "GitHub"
    link = "https://github.com/workloads"

  [[params.social]]
    icon = "fa-brands fa-x-twitter"
    name = "X"
    link = "https://x.com/wrklds"

  [[params.social]]
    icon = "fa-brands fa-youtube"
    name = "YouTube"
    link = "https://youtube.com/c/workloads"

  [[params.social]]
    icon = "fa-brands fa-instagram"
    name = "Instagram"
    link = "https://instagram.com/wrklds"

[related]
  includeNewer = true
  threshold    = 85
  toLower      = false

  [[related.indices]]
    name   = "tags"
    weight = 80

  [[related.indices]]
    name   = "keywords"
    weight = 40

  [[related.indices]]
    name   = "date"
    weight = 10
